/- ============================================================================
   GENERATED FILE — DO NOT EDIT.
   Generated by `lakew sync` from `lean-workspace.toml`, which is authoritative.
   Regenerate with: lakew sync
   CI staleness gate: lakew check
   ============================================================================ -/
import Lake
open Lake DSL

package repo where
  enableArtifactCache := true
  restoreAllArtifacts := false

require core from "packages/core"
require «syntax» from "packages/syntax"
require tactics from "packages/tactics"
