/-
Copyright (c) 2026 Jacob Reinhold. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jacob Reinhold
-/
module

public import LakeWorkspace.Workspace
public import LakeWorkspace.Json

/-!
The Lake-version-coupled backend: how generated files are spelled.

This module is the *only* place that knows the syntax of a Lake
`lakefile.lean`, the JSON schema of `.lake/package-overrides.json`, and the
command-line surface of the pinned `lake` executable. The rendering/decision
functions are pure; process spawning lives in `LakeWorkspace.Executor`, with
one class of exceptions: `lakeScripts`/`lakeCacheServices` are read-only
probes needed *during* planning/checking (Executor imports the plan types,
so the reverse edge would cycle).
-/

public section

namespace LakeWorkspace.Backend.LakeCli

open LakeWorkspace

/-- The manifest/overrides schema version written and accepted by Lake
    (verified against `Lake.Load.Manifest.version` = "1.2.0"). -/
def schemaVersion : String := "1.2.0"

/-- Lean/Lake keywords that cannot appear bare as package names in the DSL. -/
def keywords : Array String :=
  #[ "syntax", "def", "theorem", "lemma", "axiom", "opaque", "abbrev", "inductive"
   , "structure", "class", "instance", "package", "require", "import", "from"
   , "with", "where", "end", "namespace", "section", "open", "if", "then"
   , "else", "match", "do", "let", "fun", "macro", "elab", "example", "macro_rules"
   , "lean_lib", "lean_exe", "extern_lib", "target", "script", "post_update"
   , "default_target", "test_runner" ]

/-- Quote a package name for Lake DSL when it is not a plain identifier
    or collides with a keyword. -/
def quoteIdent (s : String) : String :=
  let plain := !s.isEmpty && (s.toList.head!.isAlpha || s.toList.head! == '_') &&
    s.toList.all fun c => c.isAlphanum || c == '_' || c == '\''
  if plain && !keywords.contains s then s else s!"«{s}»"

/-- The prominent do-not-edit header for generated files (doc §2). -/
def generatedHeader : String :=
  "/- ============================================================================\n" ++
  "   GENERATED FILE — DO NOT EDIT.\n" ++
  "   Generated by `lakew sync` from `lean-workspace.toml`, which is authoritative.\n" ++
  "   Regenerate with: lakew sync\n" ++
  "   CI staleness gate: lakew check\n" ++
  "   ============================================================================ -/\n"

/-- Render the virtual root `lakefile.lean`. -/
def renderRootLakefile (ws : Workspace) : String := Id.run do
  let mut out := generatedHeader
  out := out ++ "import Lake\nopen Lake DSL\n\n"
  -- Cache policy propagates from the workspace root to every member that
  -- does not set its own value (Lake `PackageConfig` documentation).
  let restoreAll := ws.config.cacheRestore != "requested-only"
  out := out ++ s!"package {quoteIdent ws.config.name} where\n"
  out := out ++ s!"  enableArtifactCache := {ws.config.cacheLocal}\n"
  out := out ++ s!"  restoreAllArtifacts := {restoreAll}\n"
  out := out ++ "\n"
  for m in ws.members do
    out := out ++ s!"require {quoteIdent m.name} from \"{m.relDir.toString}\"\n"
  return out

/-- Render one member entry of `.lake/package-overrides.json`.
    Field set and version match Lake's own `Manifest.saveEntries`. -/
def renderOverrideEntry (m : MemberPkg) : Json :=
  .obj #[
    ("type", .str "path"),
    ("scope", .str ""),
    ("name", .str m.name),
    ("manifestFile", .null),
    ("inherited", .boolean false),
    ("dir", .str m.relDir.toString),
    ("configFile", .str "lakefile.lean") ]

/-- Render `.lake/package-overrides.json`: every workspace package name
    resolves to its local member path, even transitively (Cargo `[patch]`). -/
def renderOverrides (ws : Workspace) : Json :=
  .obj #[
    ("schemaVersion", .str schemaVersion),
    ("packages", .arr (ws.members.map renderOverrideEntry)) ]

private def renderRequire (r : RequireDecl) : Json :=
  match r.src with
  | .path dir => .obj #[("name", .str r.name), ("type", .str "path"),
                         ("dir", .str dir.toString)]
  | .git url rev? => .obj #[("name", .str r.name), ("type", .str "git"),
                             ("url", .str url),
                             ("rev", match rev? with | some r => .str r | none => .null) ]

/-- Render `.lake/workspace/metadata.json`: the canonical workspace model
    snapshot, for tooling and `lakew metadata`. -/
def renderMetadata (ws : Workspace) : Json :=
  let memberJson (m : MemberPkg) : Json := .obj #[
    ("name", .str m.name),
    ("dir", .str m.relDir.toString),
    ("moduleRoots", .arr (m.moduleRoots.map .str)),
    ("modules", .arr (m.modules.map .str)),
    ("requires", .arr (m.requires.map renderRequire)) ]
  let edgeJson (e : String × String) : Json :=
    .arr #[.str e.1, .str e.2]
  let groupJson (g : String × Array String) : Json :=
    .obj #[("name", .str g.1), ("members", .arr (g.2.map .str))]
  .obj #[
    ("lakew", .num 1),
    ("toolchain", .str ws.toolchain),
    ("rootPackage", .str ws.config.name),
    ("members", .arr (ws.members.map memberJson)),
    ("edges", .arr (ws.edges.map edgeJson)),
    ("groups", .arr (ws.config.groups.map groupJson)),
    ("defaultMembers", .arr (ws.config.defaultMembers.map .str)),
    ("fingerprint", .str (Workspace.fingerprint ws)) ]

/-- Every file `lakew sync` generates, as `(path relative to root, contents)`. -/
def generatedFiles (ws : Workspace) : Array (FilePath × String) :=
  #[ (⟨"lakefile.lean"⟩, renderRootLakefile ws)
   , (⟨".lake/package-overrides.json"⟩, Json.pretty (renderOverrides ws) ++ "\n")
   , (⟨".lake/workspace/metadata.json"⟩, Json.pretty (renderMetadata ws) ++ "\n") ]

/-- Probe the pinned `lake` for the workspace's declared scripts — members'
    and dependency packages' alike — as `(pkg, name)` pairs parsed from the
    `pkg/name` lines of `lake scripts`. Read-only; a failed probe (no sync
    yet, no packages materialized) yields no scripts rather than an error,
    since the caller only uses the list as a driver-detection fallback. -/
def lakeScripts (root : FilePath) : IO (Array (String × String)) := do
  let out ← IO.Process.output { cmd := "lake", args := #["scripts"], cwd := some root }
  if out.exitCode != 0 then return #[]
  return out.stdout.splitOn "\n" |>.filterMap (fun line =>
    match line.trimAscii.toString.splitOn "/" with
    | [p, n] => some (p, n)
    | _ => none) |>.toArray

/-- The configured remote cache services, parsed from `lake cache services`
    (one name per line). Read-only probe; services themselves are configured
    in the user's system config (`~/.lake/config.toml`), which lakew never
    writes — this exists so `lakew check` can validate `[cache].remote`
    against reality. A failed probe yields no services. -/
def lakeCacheServices (root : FilePath) : IO (Array String) := do
  let out ← IO.Process.output
    { cmd := "lake", args := #["cache", "services"], cwd := some root }
  if out.exitCode != 0 then return #[]
  return out.stdout.splitOn "\n"
    |>.map (·.trimAscii.toString) |>.filter (!·.isEmpty) |>.toArray

end LakeWorkspace.Backend.LakeCli

end -- public section
