/- ============================================================================
   GENERATED FILE — DO NOT EDIT.
   Generated by `lakew sync` from `lean-workspace.toml`, which is authoritative.
   Regenerate with: lakew sync
   CI staleness gate: lakew check
   ============================================================================ -/
import Lake
open Lake DSL

package cachepolicy where
  enableArtifactCache := true
  restoreAllArtifacts := false

require aaa from "packages/aaa"
require bbb from "packages/bbb"
